task:
  type: "multiclass"
  class_list: ["yes", "no", "up", "down", "stop", "go"]
  include_unknown: true
  include_background: true

data:
  background_label: "_background_noise_"

train:
  class_weights: null
  label_smoothing: 0.0